-- VINOS foto_path column - idempotent
SET @table_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'VINOS');
SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'VINOS' AND COLUMN_NAME = 'foto_path');
SET @ddl := IF(@table_exists = 1 AND @col_exists = 0, 'ALTER TABLE `VINOS` ADD COLUMN `foto_path` VARCHAR(512) NULL', 'SELECT 1');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
