CREATE TABLE IF NOT EXISTS stock_recipes (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    restaurant_id INT NOT NULL,
    name VARCHAR(180) NOT NULL,
    output_item_id BIGINT UNSIGNED NOT NULL,
    output_qty_base DECIMAL(18,4) NOT NULL,
    waste_pct DECIMAL(5,2) NOT NULL DEFAULT 0,
    prep_time_min INT NULL,
    instructions TEXT NULL,
    version INT NOT NULL DEFAULT 1,
    source ENUM('MANUAL','IMPORTED','OCR') NOT NULL DEFAULT 'MANUAL',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    active_output_item_id BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN is_active = 1 THEN output_item_id ELSE NULL END) STORED,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_stock_recipes_tenant_id (restaurant_id, id),
    UNIQUE KEY uq_stock_recipe_output (restaurant_id, active_output_item_id),
    KEY idx_stock_recipes_restaurant (restaurant_id, is_active, name),
    CONSTRAINT fk_stock_recipes_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_stock_recipes_output FOREIGN KEY (restaurant_id, output_item_id) REFERENCES stock_items(restaurant_id, id),
    CONSTRAINT chk_stock_recipe_yield CHECK (output_qty_base > 0),
    CONSTRAINT chk_stock_recipe_waste CHECK (waste_pct >= 0 AND waste_pct < 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stock_recipe_components (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    restaurant_id INT NOT NULL,
    recipe_id BIGINT UNSIGNED NOT NULL,
    stock_item_id BIGINT UNSIGNED NOT NULL,
    sub_recipe_id BIGINT UNSIGNED NULL,
    entered_qty DECIMAL(18,4) NOT NULL,
    entered_unit_id BIGINT UNSIGNED NOT NULL,
    qty_base DECIMAL(18,4) NOT NULL,
    waste_pct DECIMAL(5,2) NOT NULL DEFAULT 0,
    is_optional TINYINT(1) NOT NULL DEFAULT 0,
    notes VARCHAR(500) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_stock_recipe_components_recipe (restaurant_id, recipe_id, sort_order),
    CONSTRAINT fk_stock_recipe_components_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_stock_recipe_components_recipe FOREIGN KEY (restaurant_id, recipe_id) REFERENCES stock_recipes(restaurant_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_stock_recipe_components_sub_recipe FOREIGN KEY (restaurant_id, sub_recipe_id) REFERENCES stock_recipes(restaurant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_stock_recipe_components_item FOREIGN KEY (restaurant_id, stock_item_id) REFERENCES stock_items(restaurant_id, id),
    CONSTRAINT fk_stock_recipe_components_unit FOREIGN KEY (restaurant_id, entered_unit_id) REFERENCES stock_item_units(restaurant_id, id),
    CONSTRAINT chk_stock_recipe_component_qty CHECK (qty_base > 0),
    CONSTRAINT chk_stock_recipe_component_waste CHECK (waste_pct >= 0 AND waste_pct < 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stock_production_orders (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    restaurant_id INT NOT NULL,
    recipe_id BIGINT UNSIGNED NOT NULL,
    recipe_version INT NOT NULL,
    warehouse_id BIGINT UNSIGNED NOT NULL,
    batches DECIMAL(18,4) NOT NULL,
    qty_produced_base DECIMAL(18,4) NOT NULL,
    status ENUM('CONFIRMED','CANCELLED') NOT NULL DEFAULT 'CONFIRMED',
    idempotency_key VARCHAR(120) NOT NULL,
    actor_user_id INT NOT NULL,
    produced_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_stock_production_idempotency (restaurant_id, idempotency_key),
    UNIQUE KEY uq_stock_production_tenant_id (restaurant_id, id),
    KEY idx_stock_production_recipe (restaurant_id, recipe_id, produced_at),
    CONSTRAINT fk_stock_production_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_stock_production_recipe FOREIGN KEY (restaurant_id, recipe_id) REFERENCES stock_recipes(restaurant_id, id),
    CONSTRAINT fk_stock_production_warehouse FOREIGN KEY (restaurant_id, warehouse_id) REFERENCES stock_warehouses(restaurant_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stock_production_order_lines (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    restaurant_id INT NOT NULL,
    production_order_id BIGINT UNSIGNED NOT NULL,
    stock_item_id BIGINT UNSIGNED NOT NULL,
    planned_qty_base DECIMAL(18,4) NOT NULL,
    actual_qty_base DECIMAL(18,4) NOT NULL,
    was_untracked TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_stock_production_lines_order (restaurant_id, production_order_id),
    CONSTRAINT fk_stock_production_lines_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_stock_production_lines_order FOREIGN KEY (restaurant_id, production_order_id) REFERENCES stock_production_orders(restaurant_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_stock_production_lines_item FOREIGN KEY (restaurant_id, stock_item_id) REFERENCES stock_items(restaurant_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
