CREATE TABLE IF NOT EXISTS pos_shifts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    restaurant_id INT NOT NULL,
    terminal_key VARCHAR(64) NOT NULL DEFAULT 'main',
    opened_by INT NOT NULL,
    closed_by INT NULL,
    opening_cash_cents BIGINT NOT NULL DEFAULT 0,
    closing_cash_counted_cents BIGINT NULL,
    expected_cash_cents BIGINT NULL,
    status ENUM('OPEN','CLOSED') NOT NULL DEFAULT 'OPEN',
    opened_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at DATETIME NULL,
    notes VARCHAR(500) NULL,
    open_terminal_key VARCHAR(64) GENERATED ALWAYS AS (CASE WHEN status='OPEN' THEN terminal_key ELSE NULL END) STORED,
    PRIMARY KEY (id),
    UNIQUE KEY uq_pos_shifts_tenant_id (restaurant_id, id),
    UNIQUE KEY uq_pos_shift_open_terminal (restaurant_id, open_terminal_key),
    KEY idx_pos_shifts_restaurant (restaurant_id, status, opened_at),
    CONSTRAINT fk_pos_shifts_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT chk_pos_shift_cash CHECK (opening_cash_cents >= 0 AND (closing_cash_counted_cents IS NULL OR closing_cash_counted_cents >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_visits (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    restaurant_id INT NOT NULL,
    channel ENUM('DINE_IN','TAKEAWAY','DELIVERY') NOT NULL DEFAULT 'DINE_IN',
    table_id INT NULL,
    booking_id INT NULL,
    service_date DATE NOT NULL,
    service_type ENUM('LUNCH','DINNER','OTHER') NOT NULL DEFAULT 'OTHER',
    covers INT NOT NULL DEFAULT 0,
    status ENUM('OPEN','CLOSED','CANCELLED') NOT NULL DEFAULT 'OPEN',
    opened_by INT NOT NULL,
    closed_by INT NULL,
    opened_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at DATETIME NULL,
    version INT NOT NULL DEFAULT 1,
    open_idempotency_key VARCHAR(120) NOT NULL,
    open_table_id INT GENERATED ALWAYS AS (CASE WHEN status='OPEN' AND channel='DINE_IN' THEN table_id ELSE NULL END) STORED,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_pos_visits_tenant_id (restaurant_id, id),
    UNIQUE KEY uq_pos_visit_open_table (restaurant_id, open_table_id),
    UNIQUE KEY uq_pos_visit_open_idempotency (restaurant_id, open_idempotency_key),
    KEY idx_pos_visits_restaurant (restaurant_id, status, service_date, service_type),
    CONSTRAINT fk_pos_visits_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_pos_visits_table FOREIGN KEY (restaurant_id, table_id) REFERENCES restaurant_tables(restaurant_id, id) ON DELETE RESTRICT,
    CONSTRAINT chk_pos_visit_covers CHECK (covers >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_tickets (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    restaurant_id INT NOT NULL,
    visit_id BIGINT UNSIGNED NOT NULL,
    shift_id BIGINT UNSIGNED NULL,
    ticket_number VARCHAR(48) NOT NULL,
    status ENUM('OPEN','PAID','VOIDED','PARTIALLY_REFUNDED','REFUNDED') NOT NULL DEFAULT 'OPEN',
    subtotal_gross_cents BIGINT NOT NULL DEFAULT 0,
    discount_cents BIGINT NOT NULL DEFAULT 0,
    ticket_discount_cents BIGINT NOT NULL DEFAULT 0,
    tax_cents BIGINT NOT NULL DEFAULT 0,
    total_gross_cents BIGINT NOT NULL DEFAULT 0,
    paid_cents BIGINT NOT NULL DEFAULT 0,
    refunded_cents BIGINT NOT NULL DEFAULT 0,
    stock_status ENUM('NOT_APPLICABLE','SHADOW','COMPLETE','PARTIAL','REVERSED') NOT NULL DEFAULT 'NOT_APPLICABLE',
    creation_idempotency_key VARCHAR(120) NOT NULL,
    checkout_idempotency_key VARCHAR(120) NULL,
    opened_by INT NOT NULL,
    closed_by INT NULL,
    opened_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at DATETIME NULL,
    voided_at DATETIME NULL,
    version INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_pos_tickets_tenant_id (restaurant_id, id),
    UNIQUE KEY uq_pos_ticket_number (restaurant_id, ticket_number),
    UNIQUE KEY uq_pos_ticket_creation (restaurant_id, creation_idempotency_key),
    UNIQUE KEY uq_pos_ticket_checkout (restaurant_id, checkout_idempotency_key),
    KEY idx_pos_tickets_visit (restaurant_id, visit_id, status),
    CONSTRAINT fk_pos_tickets_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_pos_tickets_visit FOREIGN KEY (restaurant_id, visit_id) REFERENCES pos_visits(restaurant_id, id),
    CONSTRAINT fk_pos_tickets_shift FOREIGN KEY (restaurant_id, shift_id) REFERENCES pos_shifts(restaurant_id, id),
    CONSTRAINT chk_pos_ticket_money CHECK (subtotal_gross_cents >= 0 AND discount_cents >= 0 AND ticket_discount_cents >= 0 AND tax_cents >= 0 AND total_gross_cents >= 0 AND paid_cents >= 0 AND refunded_cents >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_ticket_lines (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    restaurant_id INT NOT NULL,
    ticket_id BIGINT UNSIGNED NOT NULL,
    pos_product_id BIGINT UNSIGNED NULL,
    product_name_snapshot VARCHAR(180) NOT NULL,
    product_sku_snapshot VARCHAR(64) NULL,
    quantity DECIMAL(12,3) NOT NULL,
    unit_price_gross_cents BIGINT NOT NULL,
    vat_rate_snapshot DECIMAL(5,2) NOT NULL DEFAULT 0,
    discount_cents BIGINT NOT NULL DEFAULT 0,
    line_total_gross_cents BIGINT NOT NULL,
    notes VARCHAR(500) NULL,
    course VARCHAR(40) NULL,
    status ENUM('ACTIVE','VOIDED') NOT NULL DEFAULT 'ACTIVE',
    void_reason VARCHAR(500) NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    created_by INT NOT NULL,
    voided_by INT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    voided_at TIMESTAMP NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_pos_ticket_lines_tenant_id (restaurant_id, id),
    UNIQUE KEY uq_pos_ticket_line_idempotency (restaurant_id, idempotency_key),
    KEY idx_pos_ticket_lines_ticket (restaurant_id, ticket_id, status, id),
    CONSTRAINT fk_pos_ticket_lines_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_pos_ticket_lines_ticket FOREIGN KEY (restaurant_id, ticket_id) REFERENCES pos_tickets(restaurant_id, id),
    CONSTRAINT fk_pos_ticket_lines_product FOREIGN KEY (restaurant_id, pos_product_id) REFERENCES pos_products(restaurant_id, id),
    CONSTRAINT chk_pos_ticket_line_qty CHECK (quantity > 0),
    CONSTRAINT chk_pos_ticket_line_money CHECK (unit_price_gross_cents >= 0 AND discount_cents >= 0 AND line_total_gross_cents >= 0 AND vat_rate_snapshot >= 0 AND vat_rate_snapshot <= 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_payments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    restaurant_id INT NOT NULL,
    ticket_id BIGINT UNSIGNED NOT NULL,
    method ENUM('CASH','CARD','BANK','OTHER') NOT NULL,
    amount_cents BIGINT NOT NULL,
    status ENUM('CAPTURED','VOIDED','REFUNDED') NOT NULL DEFAULT 'CAPTURED',
    provider VARCHAR(64) NULL,
    provider_reference VARCHAR(191) NULL,
    card_last4 CHAR(4) NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    received_by INT NOT NULL,
    received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_pos_payments_tenant_id (restaurant_id, id),
    UNIQUE KEY uq_pos_payment_idempotency (restaurant_id, idempotency_key),
    UNIQUE KEY uq_pos_payment_provider_ref (restaurant_id, provider, provider_reference),
    KEY idx_pos_payments_ticket (restaurant_id, ticket_id, status),
    CONSTRAINT fk_pos_payments_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_pos_payments_ticket FOREIGN KEY (restaurant_id, ticket_id) REFERENCES pos_tickets(restaurant_id, id),
    CONSTRAINT chk_pos_payment_amount CHECK (amount_cents > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_refunds (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    restaurant_id INT NOT NULL,
    ticket_id BIGINT UNSIGNED NOT NULL,
    amount_cents BIGINT NOT NULL,
    reason VARCHAR(500) NOT NULL,
    payment_method ENUM('CASH','CARD','BANK','OTHER') NOT NULL,
    provider_reference VARCHAR(191) NULL,
    status ENUM('COMPLETED','VOIDED') NOT NULL DEFAULT 'COMPLETED',
    idempotency_key VARCHAR(120) NOT NULL,
    created_by INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_pos_refunds_tenant_id (restaurant_id, id),
    UNIQUE KEY uq_pos_refund_idempotency (restaurant_id, idempotency_key),
    KEY idx_pos_refunds_ticket (restaurant_id, ticket_id, status),
    CONSTRAINT fk_pos_refunds_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_pos_refunds_ticket FOREIGN KEY (restaurant_id, ticket_id) REFERENCES pos_tickets(restaurant_id, id),
    CONSTRAINT chk_pos_refund_amount CHECK (amount_cents > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_refund_lines (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    restaurant_id INT NOT NULL,
    refund_id BIGINT UNSIGNED NOT NULL,
    ticket_line_id BIGINT UNSIGNED NOT NULL,
    quantity DECIMAL(12,3) NOT NULL,
    amount_cents BIGINT NOT NULL,
    restock_requested TINYINT(1) NOT NULL DEFAULT 0,
    reason VARCHAR(500) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_pos_refund_lines_refund (restaurant_id, refund_id),
    CONSTRAINT fk_pos_refund_lines_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_pos_refund_lines_refund FOREIGN KEY (restaurant_id, refund_id) REFERENCES pos_refunds(restaurant_id, id),
    CONSTRAINT fk_pos_refund_lines_ticket_line FOREIGN KEY (restaurant_id, ticket_line_id) REFERENCES pos_ticket_lines(restaurant_id, id),
    CONSTRAINT chk_pos_refund_line CHECK (quantity > 0 AND amount_cents >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_audit_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    restaurant_id INT NOT NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id BIGINT UNSIGNED NOT NULL,
    action VARCHAR(64) NOT NULL,
    before_json JSON NULL,
    after_json JSON NULL,
    actor_user_id INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_pos_audit_entity (restaurant_id, entity_type, entity_id, created_at),
    CONSTRAINT fk_pos_audit_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_daily_sequences (
    restaurant_id INT NOT NULL,
    business_date DATE NOT NULL,
    sequence_type VARCHAR(32) NOT NULL,
    next_value BIGINT UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (restaurant_id, business_date, sequence_type),
    CONSTRAINT fk_pos_daily_sequences_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
