CREATE TABLE IF NOT EXISTS pos_ticket_line_stock (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    restaurant_id INT NOT NULL,
    ticket_id BIGINT UNSIGNED NOT NULL,
    ticket_line_id BIGINT UNSIGNED NOT NULL,
    stock_rule_id BIGINT UNSIGNED NULL,
    stock_item_id BIGINT UNSIGNED NOT NULL,
    warehouse_id BIGINT UNSIGNED NOT NULL,
    quantity_sold DECIMAL(12,3) NOT NULL,
    qty_base_planned DECIMAL(18,4) NOT NULL,
    status ENUM('SHADOW','APPLIED','SKIPPED_UNTRACKED','ERROR','REVERSED') NOT NULL,
    sale_movement_id BIGINT UNSIGNED NULL,
    return_movement_id BIGINT UNSIGNED NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    applied_at TIMESTAMP NULL,
    reversed_at TIMESTAMP NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_pos_line_stock_tenant_id (restaurant_id, id),
    UNIQUE KEY uq_pos_line_stock_snapshot (restaurant_id, ticket_line_id, stock_item_id, warehouse_id),
    KEY idx_pos_line_stock_ticket (restaurant_id, ticket_id, status),
    CONSTRAINT fk_pos_line_stock_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_pos_line_stock_ticket FOREIGN KEY (restaurant_id, ticket_id) REFERENCES pos_tickets(restaurant_id, id),
    CONSTRAINT fk_pos_line_stock_line FOREIGN KEY (restaurant_id, ticket_line_id) REFERENCES pos_ticket_lines(restaurant_id, id),
    CONSTRAINT fk_pos_line_stock_rule FOREIGN KEY (restaurant_id, stock_rule_id) REFERENCES pos_product_stock_rules(restaurant_id, id),
    CONSTRAINT fk_pos_line_stock_item FOREIGN KEY (restaurant_id, stock_item_id) REFERENCES stock_items(restaurant_id, id),
    CONSTRAINT fk_pos_line_stock_warehouse FOREIGN KEY (restaurant_id, warehouse_id) REFERENCES stock_warehouses(restaurant_id, id),
    CONSTRAINT chk_pos_line_stock_qty CHECK (quantity_sold > 0 AND qty_base_planned > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_stock_exceptions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    restaurant_id INT NOT NULL,
    ticket_id BIGINT UNSIGNED NOT NULL,
    ticket_line_id BIGINT UNSIGNED NULL,
    code ENUM('UNMAPPED_PRODUCT','INVALID_MAPPING','WAREHOUSE_MISSING','APPLY_FAILED') NOT NULL,
    status ENUM('OPEN','RESOLVED','IGNORED') NOT NULL DEFAULT 'OPEN',
    message VARCHAR(500) NOT NULL,
    resolved_by INT NULL,
    resolved_at TIMESTAMP NULL,
    replay_idempotency_key VARCHAR(120) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_pos_stock_exception_replay (restaurant_id, replay_idempotency_key),
    KEY idx_pos_stock_exceptions_restaurant (restaurant_id, status, created_at),
    CONSTRAINT fk_pos_stock_exceptions_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_pos_stock_exceptions_ticket FOREIGN KEY (restaurant_id, ticket_id) REFERENCES pos_tickets(restaurant_id, id),
    CONSTRAINT fk_pos_stock_exceptions_line FOREIGN KEY (restaurant_id, ticket_line_id) REFERENCES pos_ticket_lines(restaurant_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_stock_anomalies (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    restaurant_id INT NOT NULL,
    ticket_id BIGINT UNSIGNED NOT NULL,
    ticket_line_stock_id BIGINT UNSIGNED NOT NULL,
    stock_item_id BIGINT UNSIGNED NOT NULL,
    warehouse_id BIGINT UNSIGNED NOT NULL,
    quantity_after_base DECIMAL(18,4) NOT NULL,
    status ENUM('OPEN','RESOLVED') NOT NULL DEFAULT 'OPEN',
    resolved_by INT NULL,
    resolved_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_pos_stock_anomaly_snapshot (restaurant_id, ticket_line_stock_id),
    KEY idx_pos_stock_anomalies_status (restaurant_id, status, created_at),
    CONSTRAINT fk_pos_stock_anomalies_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_pos_stock_anomalies_ticket FOREIGN KEY (restaurant_id, ticket_id) REFERENCES pos_tickets(restaurant_id, id),
    CONSTRAINT fk_pos_stock_anomalies_snapshot FOREIGN KEY (restaurant_id, ticket_line_stock_id) REFERENCES pos_ticket_line_stock(restaurant_id, id),
    CONSTRAINT fk_pos_stock_anomalies_item FOREIGN KEY (restaurant_id, stock_item_id) REFERENCES stock_items(restaurant_id, id),
    CONSTRAINT fk_pos_stock_anomalies_warehouse FOREIGN KEY (restaurant_id, warehouse_id) REFERENCES stock_warehouses(restaurant_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_cover_adjustments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    restaurant_id INT NOT NULL,
    visit_id BIGINT UNSIGNED NULL,
    service_date DATE NOT NULL,
    service_type ENUM('LUNCH','DINNER','OTHER') NOT NULL DEFAULT 'OTHER',
    delta_covers INT NOT NULL,
    reason VARCHAR(500) NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    actor_user_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_pos_cover_adjustment_idempotency (restaurant_id, idempotency_key),
    KEY idx_pos_cover_adjustments_key (restaurant_id, service_date, service_type, created_at),
    CONSTRAINT fk_pos_cover_adjustments_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_pos_cover_adjustments_visit FOREIGN KEY (restaurant_id, visit_id) REFERENCES pos_visits(restaurant_id, id),
    CONSTRAINT chk_pos_cover_adjustment CHECK (delta_covers <> 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
