-- ChatGPT plugin API credentials. Coordination id: chatgpt_plugin_v1
--
-- chatgpt_plugin_tokens: one bearer token per (bo_user, restaurant). The raw
-- token is returned to the operator exactly once (generated by the
-- chatgpt-plugin-token command) and only its SHA-256 digest is stored, so a
-- database dump never yields a usable ChatGPT credential. The row pins the
-- token to a single restaurant and inherits the user's RBAC role through
-- bo_user_restaurants, so the plugin can never widen the user's ACL.
CREATE TABLE IF NOT EXISTS chatgpt_plugin_tokens (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    restaurant_id INT NOT NULL,
    token_hash CHAR(64) NOT NULL,
    label VARCHAR(128) NULL,
    scopes_json TEXT NULL,
    revoked_at TIMESTAMP NULL DEFAULT NULL,
    last_used_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_chatgpt_plugin_tokens_hash (token_hash),
    KEY idx_chatgpt_plugin_tokens_user (user_id, restaurant_id),
    KEY idx_chatgpt_plugin_tokens_restaurant (restaurant_id),
    CONSTRAINT fk_chatgpt_plugin_tokens_user FOREIGN KEY (user_id) REFERENCES bo_users(id) ON DELETE CASCADE,
    CONSTRAINT fk_chatgpt_plugin_tokens_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
